apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-alerting-provisioning
  namespace: monitoring
  labels:
    grafana_alert: "1"
data:
  alerting.yaml: |
    apiVersion: 1

# Contact Points
    contactPoints:
      - orgId: 1
        name: email-alerts
        receivers:
          - uid: email-receiver
            type: email
            settings:
              addresses: exact84@gmail.com
              subject: "[ALERT] Kubernetes Monitoring - {{ .GroupLabels.alertname }}"
              message: |
                {{ range .Alerts }}
                Alert: {{ .Annotations.summary }}
                Description: {{ .Annotations.description }}
                Severity: {{ .Labels.severity }}
                Instance: {{ .Labels.instance }}
                Started: {{ .StartsAt }}
                {{ end }}
            disableResolveMessage: false

# Notification Policies
    policies:
      - orgId: 1
        receiver: email-alerts
        group_by: ['alertname', 'cluster', 'service']
        group_wait: 10s
        group_interval: 5m
        repeat_interval: 12h
        routes:
          - receiver: email-alerts
            matchers:
              - severity = warning
            group_wait: 10s
            group_interval: 5m
            repeat_interval: 4h
          - receiver: email-alerts
            matchers:
              - severity = critical
            group_wait: 5s
            group_interval: 2m
            repeat_interval: 1h

# Alert Rules
    groups:
      - orgId: 1
        name: NodeAlerts
        folder: Infrastructure
        interval: 1m
        rules:
          - uid: high-cpu-usage
            title: High CPU Usage Alert
            condition: A
            data:
              - refId: A
                relativeTimeRange:
                  from: 600
                  to: 0
                datasourceUid: prometheus
                model:
                  expr: 100 - (avg by (instance) (irate(node_cpu_seconds_total{mode="idle"}[2m])) * 100) > 70
                  interval: ""
                  legendFormat: "{{instance}}"
                  refId: A
            noDataState: NoData
            execErrState: Alerting
            for: 1m
            annotations:
              summary: "High CPU usage detected on node {{$labels.instance}}"
              description: "CPU usage is above 70% for more than 1 minute on node {{$labels.instance}}. Current value: {{$value}}%"
            labels:
              severity: warning
              team: infrastructure
          - uid: low-memory-available
            title: Low Memory Available Alert
            condition: B
            data:
              - refId: B
                relativeTimeRange:
                  from: 600
                  to: 0
                datasourceUid: prometheus
                model:
                  expr: (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) < 0.25
                  interval: ""
                  legendFormat: "{{instance}}"
                  refId: B
            noDataState: NoData
            execErrState: Alerting
            for: 1m
            annotations:
              summary: "Low memory available on node {{$labels.instance}}"
              description: "Available memory is below 25% for more than 1 minute on node {{$labels.instance}}. Current available: {{$value}}%"
            labels:
              severity: critical
              team: infrastructure
