apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kaniko-rbac-manager
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log", "secrets", "configmaps", "services", "serviceaccounts"]
    verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets"]
    verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["roles", "rolebindings"]
    verbs: ["get", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["pods/attach"]
    verbs: ["create", "get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kaniko-rbac-manager-binding
subjects:
  - kind: ServiceAccount
    name: default
    namespace: jenkins
roleRef:
  kind: ClusterRole
  name: kaniko-rbac-manager
  apiGroup: rbac.authorization.k8s.io
