name: Terraform Task 1 Workflow

on:
  push:
    branches:
      - task_1
  pull_request:
    branches:
      - task_1

permissions:
  id-token: write 
  contents: read 

jobs:
  terraform-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.2

      - name: Terraform Init
        run: terraform init -backend-config="bucket=${{ env.YOUR_S3_BUCKET_FOR_TERRAFORM_STATE }}" -backend-config="key=terraform.tfstate" -backend-config="region=${{ env.YOUR_AWS_REGION }}"
        env:
          YOUR_S3_BUCKET_FOR_TERRAFORM_STATE: my-task1-s3-bucket-777
          YOUR_AWS_REGION: us-east-1 

      - name: Terraform Format Check 
        run: terraform fmt -check

  terraform-plan:
    runs-on: ubuntu-latest
    needs: terraform-check

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: "arn:aws:iam::156207844051:role/GithubActionsRole"
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.2

      - name: Terraform Init
        run: terraform init -backend-config="bucket=${{ env.YOUR_S3_BUCKET_FOR_TERRAFORM_STATE }}" -backend-config="key=terraform.tfstate" -backend-config="region=${{ env.YOUR_AWS_REGION }}"
        env:
          YOUR_S3_BUCKET_FOR_TERRAFORM_STATE: my-task1-s3-bucket-777
          YOUR_AWS_REGION: us-east-1 

      - name: Terraform Plan
        run: terraform plan -input=false

  terraform-apply:
    runs-on: ubuntu-latest
    needs: terraform-plan 

    if: github.event_name == 'push' && github.ref == 'refs/heads/task_1'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: "arn:aws:iam::156207844051:role/GithubActionsRole"
          aws-region: us-east-1 

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.2

      - name: Terraform Init
        run: terraform init -backend-config="bucket=${{ env.YOUR_S3_BUCKET_FOR_TERRAFORM_STATE }}" -backend-config="key=terraform.tfstate" -backend-config="region=${{ env.YOUR_AWS_REGION }}"
        env:
          YOUR_S3_BUCKET_FOR_TERRAFORM_STATE: my-task1-s3-bucket-777
          YOUR_AWS_REGION: us-east-1 

      - name: Terraform Apply 
        run: terraform apply -auto-approve -input=false
